// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3U3mD2IORWvKlfd1GnrY91fpIQu3Sw-8',
    appId: '1:897512830722:android:600db65d5523e85631b41b',
    messagingSenderId: '897512830722',
    projectId: 'tebiyu-d9904',
    storageBucket: 'tebiyu-d9904.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhn0MfIt7R-LeG07k8EIvoINLR31UVQGk',
    appId: '1:897512830722:ios:3b84f07dd292712e31b41b',
    messagingSenderId: '897512830722',
    projectId: 'tebiyu-d9904',
    storageBucket: 'tebiyu-d9904.firebasestorage.app',
    iosClientId:
        '897512830722-f4170fon40rpusaftelar93kfdbnnqip.apps.googleusercontent.com',
    iosBundleId: 'com.tebiyu.tebiyu',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD92pxLDP14MxG0IcBjf5D3LvKPyE6pQVU',
    appId: '1:897512830722:web:bff814eb86f6b65731b41b',
    messagingSenderId: '897512830722',
    projectId: 'tebiyu-d9904',
    authDomain: 'tebiyu-d9904.firebaseapp.com',
    storageBucket: 'tebiyu-d9904.firebasestorage.app',
    measurementId: 'G-D92N0N2D7G',
  );
}
